### ISSUE TITLE
How to change the NPC Kill multiplier to a constant value and the Max Level?

### ISSUE THREAD

**Issue by RolfStridskjold** [Guthen/guthlevelsystem#10]
Hi there! This isn't A Issue more like A question and a little help. I'm trying to understand how to set up Guthlevelsystem on a Sandbox Gamemode. I tried to test around and change variables in the sv_config.lua file but I can't really get it to work the way i want it to. Is there anyway to change how the multipliers work when you kill npcs, I want it to give just 1 exp everytime you kill a npc regardless of its maxhealth? And have max level 100.

**Comment by Guthen** [comment]
Hey! sure you can do that with this system in the **config file**:

To give a constant value when killing NPCs, replace the code from [here](https://github.com/Guthen/guthlevelsystem/blob/master/lua/guthlevelsystem/sh_config.lua#L164) (line 164) to this:
```lua
return 1
```

To change the maximum level, just replace `50` by `100` at the [6th line](https://github.com/Guthen/guthlevelsystem/blob/master/lua/guthlevelsystem/sh_config.lua#L6)

Hope that'll resolve the problem :)

**Comment by RolfStridskjold** [comment]
It works perfect! Really appreciate you even giving me your time! Thanks alot!!

**Comment by Guthen** [comment]
no problem, have fun! ;)
