### ISSUE TITLE
How can I add in my own addons a way to add xp on action?

### ISSUE THREAD

**Issue by clementinise** [Guthen/guthlevelsystem#11]
My english is bad sorry, will try to explain at best!

I have made an addon so people can buy fruits from other player stands, what function or hook could I use in my buy function so players will be given xp? I hope I'm understandable

Just saw https://github.com/Guthen/guthlevelsystem/blob/6f58618cee02d65b867c281920c61474912e5f83/lua/guthlevelsystem/sv_players.lua#L249 I guess this is it x)

**Comment by Guthen** [comment]
Hey @clementinise 

You can add XPs serverside with `PLAYER:gls_add_xp( num, is_silent=false )` so yeah, you guess it :)

**Comment by clementinise** [comment]
> Hey @clementinise
> 
> You can add XPs serverside with `PLAYER:gls_add_xp( num, is_silent=false )` so yeah, you guess it :)

Thats a quick answer! Yeah I should have watch at the code before making an issue ticket x)

**Comment by Guthen** [comment]
No worries, have fun :)
