### ISSUE TITLE
Add XP Rank Multiplier

### ISSUE THREAD

**Issue by Certurix** [Guthen/guthlevelsystem#8]
### Description

Add a rank multiplicator which will multiplicate the OnNPCKilledXP, PlayerDeathXP and ByPlayingXP parameters by the multiplicator assigned to each rank (see an example of how config file would looks like)

The main goal is to have a rank multiplicator for specific groups, usefull for servers who want to give more XP for VIP or admin.

### Config File
The example config file:
```
guthlevelsystem.RanksMultiplicators = {
    ["superadmin"] = 2.5,
    ["vip"] = 2,
}
```

**Comment by Guthen** [comment]
Just pushed the changes, tell me if it's working as intended
